# Generated by Django 3.2.20 on 2023-08-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.PositiveIntegerField(choices=[(1, 'system admin'), (2, 'corporate admin'), (3, 'farmer')]),
        ),
    ]
