# Generated by Django 3.2.20 on 2023-08-30 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('badssys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropsales',
            name='saledate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
